### ISSUE TITLE
Attribute "dev" is not working properly

### ISSUE THREAD

**Issue by runarb** [fabric-ds/elements#27]
`<f-broadcast dev="false" url="some-url"></f-broadcast>` is fetching from [dev.finn.no](http://dev.finn.no/). The only way to make it fetch from [www.finn.no](http://www.finn.no/) is to remove the dev attribute completely.

**Comment by Skadefryd** [comment]
As mentioned in this [pull Req](https://github.com/fabric-ds/elements/pull/28). this is will be resolved differently in the next iteration of Broadcast.
